### PR TITLE
Bug/repeatable battlecries

### PR DESCRIPTION
**Pull request by MrHen**
Fixes a few bugs here and there and makes the random repeatable tests easier to run and diagnose.

The main advantage to the random game test is finding bugs like the Illidan issue that was fixed in this PR. Once we can run random repeatable tests consistently we should be able to start creating test cases from external replay data which will help us find non-fatal bugs in the mechanics.

But that's a ways off, still. I haven't seen any useful replay formats for Hearthstone yet.

### CODE REVIEW

**Comment by MrHen** [comment]
This failed travis because I used `String.join` which was apparently added in Java 1.8. Do we want to stay on 1.7 or can I bump the travis run to use 1.8?

**Comment by oyachai** [comment]
I don't have any problems moving to 1.8.  I'll make the changes to Travis in a bit.

**Comment by oyachai** [comment]
Move Travis over to 1.8.  Is this pull good to go otherwise?

**Comment by MrHen** [comment]
Yes. It passed `gradlew check` locally.

**Pull request merged**
